clean/iptv_clean_radio.m3u

added 
Antenne Thüringen(Logo missing, placeholder)
MDR Jump (Logo missing, placeholder)
MDR Thüringen(Logo missing, placeholder)
Landeswelle Thüringen(Logo missing, placeholder)

added radio stations

---

clean/iptv_clean_tv.m3u

Stellt sendebetrieb ein, variable Streamadresse

Deleted RTL II You, Disney Channel

---

iptv/clean/clean.m3u
iptv/clean/clean_tv.m3u
iptv/clean/clean_tv_main.m3u
iptv/kodi/kodi.m3u
iptv/kodi/kodi_tv.m3u
iptv/kodi/kodi_tv_main.m3u
iptv/pipe/pipe.m3u
iptv/pipe/pipe_tv.m3u
iptv/pipe/pipe_tv_main.m3u

fixes #221 
just replaced https://mcdn.daserste.de/daserste/de/profile7/playlist.m3u8 with https://mcdn.daserste.de/daserste/de/master_3744.m3u8

fix stream url of 'Das Erste'

---

iptv/source.yaml

fixed euronews and br nord

---

iptv/source.yaml

Nikelodeon hat die quali runtergeschraubt

fix Nickelodeon and Kika

---

iptv/source.yaml

New Channel // MTV Music 24

---

iptv/source.yaml

fix DELUXE MUSIC

---

iptv/source.yaml

fix Das Erste HD

---

iptv/source.yaml

Sorry for the two PRs, I decided to go thru the list and change all of ORF's radio URLs.

Orf radio new urls

---

iptv/source.yaml

fix SWR Baden-Württemberg HD / SWR Rheinland-Pfalz HD

---

iptv/source.yaml

Fix ARD Event 1 + 2 / Sportschau HD 1 / HD 2

---

iptv/source.yaml

ABC News fix

---

iptv/source.yaml

added Rock Antenne Heavy-Metal

---

iptv/source.yaml

Fix NDR Hamburg HD

---

iptv/source.yaml

Fix ARD ONE HD

---

iptv/source.yaml

Radio 2000

---

iptv/source.yaml

Orange 94.0

---

iptv/source.yaml

Hab die neuen Adressen für RBB aus dem Forum mal eben eingefügt.

Links für RBB Berlin und BRAndenburg aktualisiert

---

iptv/source.yaml

Just checked the links for NDR and updated them

Fixed various NDR Links

---

iptv/source.yaml

Additionally change the main nice station URL from aac/64 to mp3/256

Remove offline nice DELUXE and nice URBAN channels

---

iptv/source.yaml

Zeigt derzeit die SWR1 BW Hitparade Live Visual Radio

SWR Event 3

---

iptv/source.yaml

Taken from webplayer https://planetradio.co.uk/scala-radio/player/
Fixes 404 Not Found error

Fix Scala channel

---

iptv/dash/dash_tv.m3u

nice sendet nur noch mit Token, Link defekt - daher entfernt.

nice entfernt

---

iptv/dash/dash_tv.m3u

Reverts jnk22/kodinerds-iptv#482

Revert "nice entfernt"

---

iptv/source.yaml

I have updated the DLF Streamslinks to the 192kbit AAC Version.

Switched to AAC Streams for DLF Channels

---

iptv/source.yaml

Neue URL KielTV

---

iptv/source.yaml

Neue URL wie in #472 beschrieben.

Neue URL für Parlamentsfernsehen 2

---

.github/workflows/update_m3u.yml

Das Skript sollte m3u8-Dateien nicht für Merge Requests erstellen.

Automatisches Generieren der m3u8-Dateien nur auf 'master'

---

iptv/source.yaml

Neue Stream-URL eingefügt, jetzt adaptiv in 1080p, daher HD auf yes gesetzt.

Okto aktualisiert

---

iptv/source.yaml

http://www.melodie.tv/cms/index.php/stream
https://youtu.be/1nHkPNp4Yc0
Logo: http://www.melodie.tv/cms/index.php/programmplan/medien #523

Add Melodie TV

---

scripts/yaml_to_m3u.py

@jnk22 @freddii @plata schaut euch das Script mal bitte an.
Ich habe nur eine Zeile geändert um aus den youtube links den Aufruf für das Kodi Plugin zu machen.
Hat bei mir problemlos funktioniert, prüft das aber bitte noch mal nach.

Added function to replace youtube url with Plugin uri for Kodi

---

iptv/source.yaml

ServusTV has changed its infrastructure lately.

Update ServusTV stream

---

iptv/source.yaml

Hopefully the right Stream Link. Bloomberg has several, i took the one for the EU.

New Link for Bloomberg #543

---

iptv/source.yaml

New Link for Deluxe Music, dont know how permanent that is.

New Link for DeluxeMusik #531

---

iptv/source.yaml

Adds a stream which continuously repeats the latest news broadcasts.

Add WELT News Loop Stream

---

iptv/source.yaml

Streams available at: https://www.adultswim.com/streams/

add adult swim marathon streams

---

iptv/source.yaml

fix: Welt TV urls

---

iptv/source.yaml

PNG to add submitted [here](https://lutim.ggc-project.de/MY5yQBcQ.png).

Welt der Wunder (SD) added

---

iptv/source.yaml

Fix of Regio TV Bodensee/Stuttgart

---

iptv/source.yaml

Current stream/playlist according to webpage.

Support WELT 1080p livestream

---

iptv/source.yaml

use proper multi stream index.m3u8

fix / update Al Jazeera

---

iptv/source.yaml

Neue ZDF Feeds sowie URL Korrekturen

Add/Change ZDF Feeds

---

iptv/source.yaml

adapt stream URLs for all 3 regional mdr stations and hr-fernsehen

fix stream urls for mdr and hr-fernsehen

---

iptv/source.yaml

Looks like they're constantly changing the sever path... Let's see.

Fix oe24 once again

---

iptv/source.yaml

fix NHK World
https://master.nhkworld.jp/nhkworld-tv/playlist/live.m3u8

Update source.yaml fix NHK Wordl URL

---

iptv/dash/dash.m3u
iptv/dash/dash_tv.m3u
iptv/dash/dash_tv_main.m3u

fixed das erste dash
