jnk22/kodinerds-iptv

iptv/source.yaml
They've changed the URLs, old servers are no longer reachable.
=> Fix Ö1, FM4 radio URLs

iptv/source.yaml
I have updated the Links for the Deutsche Welle stream according to what i have found via the Developer Tools on their Website.
=> Link Update for Deutsche Welle DE/EN/ES and Deutsche Welle Plus

iptv/source.yaml
Geänderte Streaming URL für Arte TV wie bereits im Forum erwähnt.
=> Neue URL für ARTE HD und NDR HD

iptv/source.yaml
Beim letzten Update für Arte wurden die alten NDR Adresse aus irgendeinem Grund mit in den Commit gepackt.
War mein Fehler. habe die jetzt hoffentlich wieder richtig hinzugefügt.
Sorry.
=> Noch ein Fix für NDR

iptv/source.yaml
Auch die französische URL hat sich geändert, siehe #448.
=> Fix Arte FR

iptv/source.yaml
Der alte Link war nicht erreichbar, also habe ich von https://www.br-klassik.de/ einen neuen Link besorgt.
Die übrigen *.cast.addradio.de Links scheinen noch zu funktionieren.
=> Fix BR-Klassik URL

iptv/source.yaml
Von Web-Livestream unter https://www.erfpop.de/radioplayer/ und https://www.erfplus.de/radioplayer/ übernommen.
=> Fix ERF (Plus|Pop) streaming URLs

iptv/source.yaml
With mpv, the current URL doesn't work (tls error).
This follows only the 301 permanent redirect from the previous
http://nrj.de/sachsen to https://scdn.nrjaudio.fm/adwz1/de/33013/mp3_128.mp3
=> Fix RADIO ENERGY Sachsen

iptv/source.yaml
Zum 01.09.2021 wurde der Wechsel des CDNs von addradio.de
zu rndfnk.com für (fast) alle öffenlich-rechtlichen Sender
vollzogen. Der Pfad der URLs blieb dabei identisch, nur der Hostname
ändert sich von *.addradio.de zu dispatcher.rndfnk.com.
Siehe https://www.br.de/unternehmen/inhalt/technik/livestreams-hilfe100.html
Daher wurden zunächst alle URLs mit
`sed -i -E 's@https?://.+\.addradio\.de/(.*)@https://dispatcher.rndfnk.com/\1@' iptv/source.yaml`
geändert und bei Nichtverfügbarkeit zurückgeändert.
BR:
Damit funktionieren die Angebote des BR wieder.
RBB:
Der RBB hat den Wechsel wohl noch nicht vollzogen, dort funktionieren
nur die alten Adressen.
HRinfo:
Dieser Kanal wird auf dem neuen CDN nicht mehr im davor verwendeten Format mp3/128
ausgestrahlt. Die offiziellen Links unter …
=> CDN-Wechsel der öffentlich-rechtlichen Sender

iptv/source.yaml
Die alte URL ist nun ein ungültiger Hostname.
Die neue URL wird im Webplayer unter
https://www.erf.de/hoeren-sehen/erf-mediathek/erf-web-tv/4072
abgerufen.
=> Fix ERF 1 Tv-Sender

iptv/source.yaml
Avoids error: Failed to resolve hostname icecast.thisisdax.com
URL from https://www.globalplayer.com/live/lbc/uk/
=> Fix LBC UK radio station

iptv/source.yaml
Alter Stream wurde abgeschaltet. Durch neuen ersetzt und aufgrund Anpassung (adaptiv bis 720p) HD auf yes gesetzt.
=> Hamburg 1 Stream aktualisiert

iptv/source.yaml
Maybe we should consider to remove the RT Streams from the list.
They show constant russian war propaganda, and i dont think they are a source of valid information regarding Russia's attack on Ukraine.
=> Remove all Russia Today Streams because of Russia's attack on Ukraine

CONTRIBUTING.md
As stated in #570, the current requirements for new/updated streams were not clearly defined before.
This PR updates the **CONTRIBUTING.md** file regarding the stream quality (i.e. master vs. direct streams: 1080p, 720p, ...):
- If available, only use `master` streams for new/updated streams.
- Short description and example added.
=> Update CONTRIBUTING.md regarding preferred stream quality

iptv/source.yaml
=> fix: update NDR channels

iptv/source.yaml
Fixes n-4-14.dcs.redcdn.pl: Name or service not known.
New URL found at https://player.radiozet.pl/
=> Fix Radio ZET URL

iptv/source.yaml
The new URL was found at https://www.koelncampus.com/sender/livestream/
=> Fix Köln Campus radio URL

iptv/source.yaml
The previous URL gives a 403 Forbidden error.
The new URL was found at https://www.unserding.de/unserding/musik/webradio/ The link http://streaming01.sr-online.de/unserding_2.m3u references http://liveradio.sr.de/sr/ud/mp3/128/stream.mp3?aggregator=custom1
=> Fix unserding URL

iptv/source.yaml
The domain name stream.rockland.de doesn't resolve anymore.
Through the webplayer at https://radioplayer.rockland.de/ I found https://streams.rockland.de/ which conveniently links to the country-wide stream.
=> Fix Rockland Radio URL

iptv/source.yaml
The previous URL http://stream.blackbeatslive.de/ gives HTTP errors. Instead use the official m3u containing alternative URLs, among them http://stream.blackbeats.fm/
=> Fix BlackBeats.FM URL

iptv/source.yaml
The old hostname stream.absolutradio.de doesn't resolve to IP addresses.
The new URLs are taken from the web player at https://absolutradio.de/
There seem to be more streams available, but I haven't added them for now.
=> Fix absolut radio links

iptv/source.yaml
The removed URLs all return 404.
On https://audiostreams.deluxemusic.tv/ and
https://deluxemusic.de/ are no mentions of the broken radio stations.
=> Cleanup discontinued deluxe music stations

iptv/source.yaml
Use the official m3u's from https://www.erf.de/hoeren-sehen/empfang/8628 (HTTPS by me).
Additionally rename ERF Pop to ERF Jess (see https://de.wikipedia.org/wiki/ERF_Jess#Geschichte )
=> Fix ERF URLs & rename

iptv/source.yaml
The previous URL gave a HTML error page.
The new URL was found at https://myradioonline.ro/fm-radio-manele
=> Fix Radio Manela URL

iptv/source.yaml
The new URL is used at https://www.kronehit.at/player/radioplayer/?channel=3
* Use HTTPS for kronehit
=> Fix kronehit dance URL

iptv/source.yaml
* Found the new URL at https://www.radiobob.de/radiobob/empfang/livestream
* Consistently use HTTPS for radio bob stations.
=> Fix radio bob blues URL

README.md
https://iptvnator.vercel.app/ unterstützt seit heute auch Audio-Only Channel
=> Readme: Link zum direkten Abspielen der Radio-Liste hinzugefügt

iptv/source.yaml
=> Remove dead WELTNewsLoop.de
